# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "LoggerTest" do
    pod 'NSLogger', :head
end

target "LoggerTestTests" do
    pod 'NSLogger', :head
end
