# Uncomment this line to define a global platform for your project
platform :ios, "9.0"

target "LoggerTest" do
    pod 'NSLogger', :git => 'https://github.com/fpillet/NSLogger.git', :commit => 'HEAD'
end

target "LoggerTestTests" do
    pod 'NSLogger', :git => 'https://github.com/fpillet/NSLogger.git', :commit => 'HEAD'
end
